services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    networks:
      - net1

  writer:
    build:
      context: ./writer
    container_name: writer
    depends_on:
      - postgres
    networks:
      - net1

  reader:
    build:
      context: ./reader
    container_name: reader
    depends_on:
      - postgres
    ports:
      - 8071:5000
    networks:
      - net1
    
networks:
  net1:
    driver: bridge
